<?binding.jca DBConn_db.jca?>
<wsdl:definitions name="DBConn" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseIntegration/DBIntegration/DBConn" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DatabaseIntegration/DBIntegration/DBConn" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBConn">
    <plt:partnerLinkType name="DBConn_plt">
        <plt:role name="DBConn_role">
            <plt:portType name="tns:DBConn_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DBConn" schemaLocation="xsd/DBConn_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DBConnSelect_inputParameters">
        <wsdl:part name="DBConnSelect_inputParameters" element="top:DBConnSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CountriesCollection_msg">
        <wsdl:part name="CountriesCollection" element="top:CountriesCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBConn_ptt">
        <wsdl:operation name="DBConnSelect">
            <wsdl:input message="tns:DBConnSelect_inputParameters"/>
            <wsdl:output message="tns:CountriesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
